#! /bin/bash
container=$(buildah from ubuntu:xenial)

buildah run $container \
    apt-get update -y
buildah run $container \
    apt-get install -y \
    ant \
    default-jdk-headless \
    git \
    libmysql-java \
    tomcat8

buildah run $container \
    git clone https://github.com/FutureGatewayFramework/APIServerDaemon.git
buildah config \
    --workingdir /APIServerDaemon \
    $container

#buildah copy $container \
#    files/APIServerDaemon.patch \
#    ./
#buildah run $container \
#    bash -c 'patch -p0 < APIServerDaemon.patch'

buildah run $container \
    ant all
buildah run $container \
    cp /APIServerDaemon/dist/APIServerDaemon.war /var/lib/tomcat8/webapps/ROOT.war
buildah run $container \
    ln --symbolic /usr/share/java/mysql-connector-java.jar /var/lib/tomcat8/lib/
buildah run $container \
    find /var/lib/tomcat8/webapps/ROOT/ /APIServerDaemon/ /root/.ivy2/ -delete

buildah config \
    --entrypoint '[ "/usr/share/tomcat8/bin/catalina.sh" ]' \
    --cmd 'run' \
    --env CATALINA_BASE=/var/lib/tomcat8 \
    --port 8080 \
    --workingdir / \
    $container

buildah commit $container eosc/apiserverdaemon
buildah rm $container
