---
- name: check if sudo is present
  stat:
    path: /usr/bin/sudo
  register: sudo

- name: install sudo if not present
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - libssl-dev
    - sudo
  become: yes
  become_method: su
  when: not sudo.stat.exists

- name: install dependencies (ant, default-jdk, git, tomcat8)
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - ant
    - default-jdk
    - git
    - tomcat8
  become: true

- name: clean apt cache
  command: apt-get clean
  become: true

- name: git-clone main repository
  git:
    dest: '{{ apiserverdaemon_install_dir }}'
    repo: '{{ apiserverdaemon_git_repo_url }}'
  become: true
  become_user: tomcat8

- name: build the artifact
  command: /usr/bin/ant all
  args:
    chdir: '{{ apiserverdaemon_install_dir  }}'
    creates: '{{ apiserverdaemon_war }}'
  become: true
  become_user: tomcat8

- name: copy the artifact to tomcat's directory
  copy:
    remote_src: yes
    src: '{{ apiserverdaemon_war }}'
    dest: /var/lib/tomcat8/webapps/
  become: true

- name: remove leftover files
  file:
    path: '{{ apiserverdaeon_install_dir }}'
    state: absent
  become: true
  become_user: tomcat8
