---
- name: install dependencies (git, mysql)
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - git
    - mysql-server
    - python-mysqldb

- name: git-clone main repository
  git:
    dest: '{{ fgapiserver_install_dir }}'
    repo: '{{ fgapiserver_git_repo_url }}'

- name: initialize database
  mysql_db:
    name: fgapiserver
    state: import
    target: '{{ fgapiserver_install_dir }}/fgapiserver_db.sql'
