version: '3'

services:
  fgdb:
    image: eosc/fgdb

  fgapiserver:
    image: eosc/fgapiserver
    links:
      - fgdb
    ports:
      - 8080:80

  apiserverdaemon:
    image: eosc/apiserverdaemon
    links:
      - fgdb
      - fgapiserver
